# Generated by Django 5.1.6 on 2025-02-28 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=30, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('tag', models.CharField(max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
